github steps

diff --git a/deploy/github b/deploy/github
--- a/deploy/github
+++ b/deploy/github
@@ -1,5 +1,36 @@
 #!/bin/bash
 
+vercomp () {
+    if [[ $1 == $2 ]]
+    then
+        return 0
+    fi
+    local IFS=.
+    local i ver1=($1) ver2=($2)
+    # fill empty fields in ver1 with zeros
+    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
+    do
+        ver1[i]=0
+    done
+    for ((i=0; i<${#ver1[@]}; i++))
+    do
+        if [[ -z ${ver2[i]} ]]
+        then
+            # fill empty fields in ver2 with zeros
+            ver2[i]=0
+        fi
+        if ((10#${ver1[i]} > 10#${ver2[i]}))
+        then
+            return 1
+        fi
+        if ((10#${ver1[i]} < 10#${ver2[i]}))
+        then
+            return 2
+        fi
+    done
+    return 0
+}
+
 if [[ $# -ne 1 ]]; then
     echo -n "Wrong number of arguments. You must supply Limix version "
     echo "as the first argument."
@@ -13,7 +44,71 @@ export REMOTE_BRANCH="refs/heads/production"
 
 set -e
 
-echo "CI_BRANCH=${CI_BRANCH}"
+function fetch_versions {
+
+    local msg=`github-release info -u PMBio -r limix`
+    local level=0
+    TAG_VERSIONS=
+    RELEASE_VERSIONS=
+    local IFS=$'\n'
+    for line in $msg; do
+        if [ $level -eq 2 ]; then
+            RELEASE_VERSIONS+=`echo $line | sed -E 's/^.*v([0-9]+\.[0-9]+\.[0-9]+),.*$/\1/'`
+            RELEASE_VERSIONS+=' '
+        fi
+        if [ "releases:" == "$line" ]; then
+            ((level=level+1))
+        fi
+        if [ $level -eq 1 ]; then
+            TAG_VERSIONS+=`echo $line | sed -E 's/^.*v([0-9]+\.[0-9]+\.[0-9]+) .*$/\1/'`
+            TAG_VERSIONS+=' '
+        fi
+        if [ "git tags:" == "$line" ]; then
+            ((level=level+1))
+        fi
+    done
+    echo $level
+    if [ $level -ne 2 ]; then
+        echo "Some error has occurred while fetching tag and realease versions from GitHub."
+        exit 1
+    fi
+}
+fetch_versions
+
+function gt_all {
+    local IFS=' '
+    local ver="$1"
+    local vers="$2"
+    for v in $vers
+    do
+        vercomp $ver $v
+        case $? in
+            0) op='=';;
+            1) op='>';;
+            2) op='<';;
+        esac
+        if [ $op == '<' ]; then
+            return 0
+        fi
+        if [ $op == '=' ]; then
+            return 0
+        fi
+    done
+    return 1
+}
+
+gt_all $LIMIX_VERSION $TAG_VERSIONS
+if [ $? -ne 1 ]; then
+    echo "I won't create a release because ${LIMIX_VERSION} is not greater than all other tag versions found in the PMBio repository."
+    exit 0
+fi
+
+gt_all $LIMIX_VERSION $RELEASE_VERSIONS
+if [ $? -ne 1 ]; then
+    echo "I won't create a release because ${LIMIX_VERSION} is not greater than all other release versions found in the PMBio repository."
+    exit 0
+fi
+
 COMMIT_MESSAGE=`git log -1 --pretty=%B ${CI_BRANCH} | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | grep -v '^$'`
 
 if [[ ! -z $CI_COMMIT_ID ]]; then
@@ -42,3 +137,11 @@ else
     echo "We won't try to deploy it because CI_COMMIT_ID is missing."
     exit 1
 fi
+
+# vercomp 2.5.7 2.5.6
+# case $? in
+#     0) op='=';;
+#     1) op='>';;
+#     2) op='<';;
+# esac
+# echo $op
